services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    container_name: express-api
    ports:
      - "3111:3111"
    environment:
      - NODE_ENV=development
      - PORT=3111
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - ./backend/.env

networks:
  app-network:
    driver: bridge
